# window parameters
width_sprites = 15
heigth_sprites = 16
size_sprite = 40
window_width = width_sprites * size_sprite
window_height = heigth_sprites * size_sprite
inventory_line = [".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", "."]
image_home = "ressource/home.png"
image_wall = "ressource/wall.png"
image_inventory = "ressource/inventory.png"
image_floor = "ressource/tile.png"
image_mac = "ressource/MacGyver.png"
image_guard = "ressource/Gardien.png"
image_start = "ressource/depart.png"
image_finish = "ressource/arrivee.png"
image_object_1 = "ressource/ether.png"
image_object_2 = "ressource/aiguille.png"
image_object_3 = "ressource/tube_plastique.png"
image_object_4 = "ressource/seringue.png"
image_win = "ressource/win.png"
image_lose = "ressource/lose.png"